# Generated by Django 4.2.3 on 2023-07-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_response_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
