# Generated by Django 4.2.3 on 2023-08-01 12:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_response_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='MediaContent',
        ),
    ]
