# Generated by Django 4.2.3 on 2023-08-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_advertisement_content_delete_mediacontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
